// pub mod loops;
// pub mod structs;
// pub mod traits_and_observer_pattern;
// pub mod traits_and_event_channel;
// pub mod traits_with_functions;
// pub mod enums;
// pub mod generics;
// pub mod option_enum;
// pub mod result_enum;
// pub mod hash_maps;
// pub mod lifetimes;
// pub mod closures;
// pub mod function_types;
pub mod iterators;
