// pub mod loops;
// pub mod structs;
// pub mod traits_and_observer_pattern;
// pub mod traits_and_event_channel;
// pub mod traits_with_functions;
// pub mod enums;
// pub mod generics;
// pub mod option_enum;
// pub mod result_enum;
// pub mod hash_maps;
// pub mod lifetimes;
// pub mod closures;
// pub mod function_types;
// pub mod iterators;
// pub mod smart_pointers;
// pub mod single_linked_list;
// pub mod custom_smart_pointers;
pub mod ref_counting_smart_pointers;
